### ISSUE TITLE
Deglobalization

### ISSUE THREAD

**Issue by kasp1** [apiko-rest-api/apiko#2]
As of now, the Apiko server singletons are being accessed with `global.singletonName` or `g.singletonName`, which probably makes these singletons available in user scripts and could collide with user definitions.

These singletons are only supposed to be used internally and should be only visible within Apiko.

Most of these globalizing statements can be found in [index.js](https://github.com/apiko-rest-api/apiko/blob/master/index.js#L13).

**Comment by newset** [comment]
solved
