### ISSUE TITLE
Password change endpoint

### ISSUE THREAD

**Issue by kasp1** [apiko-rest-api/apiko#21]
Perhaps we'll need a specific endpoint for changing passwords. It could be a e.g. `POST /users/password/change/userID` and it could be in the `src/users/passwordchange.js` file.

This endpoint should probably accept three parameteres:
* user ID
* old password
* new password

If old password matches, it should be replaced in the database with the new password and the server should reply with 200 OK.

Perhaps the endpoint parameters could be named literally `old` and `new`. The endpoint will also need to receive a user ID of whom is the password being changed. The endpoint definition in core.js could look like this:

```
    'POST /users/password/change/:id': {
      extendable: true,
      comment: 'Attempts to change a user password (according to specified user ID).',
      ownership: true,
      restrict: 'admin', //only the user themself and an admin can change their password
      params: {
        id: {
          required: true,
          regex: '^\\d{1,10}$',
          comment: 'User ID of whom password is being changed.'
        },
        old: {
          required: true,
          regex: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,18}$',
          comment: 'The specified user\'s old password.'
        },
        new: {
          required: true,
          regex: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,18}$',
          comment: 'The specified user\'s new password.'
        }
      },
      handlers: {
        core: './users/passwordchange'
      },
      errors: {
        7: 'Incorrect old password.',
        10: 'No such user.'
      },
      "response": {}
    }
```

The handler function could be copied from e.g. `src/users/login.js`. The received user ID, old password and new password can all be retrieved from the `req.all.paramName` object respectively (ìd`, `old`, `new`).

**Comment by alewiahmed** [comment]
I have one suggestion. When under exceptional circumstances, if the Admin is going to change a user's password, there is no need for the old password to be passed to the endpoint. the admin should only send the id of the user & the new password.
