### ISSUE TITLE
DevUi includes bulma and font projects inside it

### ISSUE THREAD

**Issue by prog-rajkamal** [apiko-rest-api/apiko#3]
this is pretty bad, instead of checking in bulma and font-awesome, we should maintain a bower.json/package.json for it.

I say move it to a different repo altogether.

**Comment by kartsims** [comment]
Yes you are right, you want to submit a PR for that ?

Let's stick with the actual `package.json` and remove the `bower_components` folder, shall we ?

Thanks for opening the issue 👍

**Comment by kartsims** [comment]
I'll move this issue to the `ui` repo
