### ISSUE TITLE
The password change endpoint sends a 500 status code.

### ISSUE THREAD

**Issue by alewiahmed** [apiko-rest-api/apiko#33]
When trying to change the password, I've sent a POST to users/password/change/:id. My post args where old: 'old password', new: 'new password', token: 'my token'. When I send it without a token, it sends me a 401 status code, which is good.

**Comment by ilabacheuski** [comment]
Yeah something goes wrong. I will fix it soon. Hope - today. But still I have to plant an onion in the garden first. Sorry!
