### ISSUE TITLE
checkRestrictions compare letters not roles

### ISSUE THREAD

**Issue by ilabacheuski** [apiko-rest-api/apiko#34]
What this lines do?
[checking restriction in ender.js](https://github.com/apiko-rest-api/apiko/blob/master/src/ender.js#L369-L374)
endpoint.restrict is a string
userRoles = ['string']

I think here is something totally wrong. Am I right?

```
var userRoles = req.session.user.role.split(',')
var hasOne = false
for (let i in endpoint.restrict) {
  if (userRoles.indexOf(endpoint.restrict[i]) >= 0) {
    hasOne = true
  }
}
```

**Comment by kasp1** [comment]
What do you think is wrong?

**Comment by ilabacheuski** [comment]
resolved
