### ISSUE TITLE
Unused verifyPassword() in data.js

### ISSUE THREAD

**Issue by ilabacheuski** [apiko-rest-api/apiko#53]
While it's cool to have a function that uniformally verify password in DB, but this one is never used and contains linting errors. [Unused function verifyPassword()](https://github.com/apiko-rest-api/apiko/blob/master/src/data.js#L125-L137)

```javascript
verifyPassword (username, password) {
      return new Promise((resolve, reject) => {
        g.data.store.models.users.findOne({ where: { username: username } }).then((user) => {
          if (bcrypt.compareSync(password, user.password)) {
            resolve()
          } else {
            reject() // !!! --->> reject requires a new Error instance
          }
        }).catch(() => {
          reject() // !!! --->> reject requires a new Error instance
        })
      })
    }
```

**Comment by kasp1** [comment]
What do you suggest? :)

**Comment by ilabacheuski** [comment]
Delete unused function. If no one use it - why is it here?

**Comment by kasp1** [comment]
Let's do

**Comment by kasp1** [comment]
Perhaps it was originally supposed to be a central function to verify password. This "central" function would be used from user/login handler and also would be available through "api" to any custom user handlers.

Maybe we could also just add it to the handler API (in this function: https://github.com/apiko-rest-api/apiko/blob/master/src/ender.js#L258 ), so it is available to everyone and just use it in user/login.js from there.

**Comment by ilabacheuski** [comment]
Now it's just a code without usage. That's all. 😄 We can change it od course. And I don't think it should be in data module. It's authorization logic.

**Comment by kasp1** [comment]
Where do you think it should be?

**Comment by ilabacheuski** [comment]
Right now I think we can delete it safely. If we need it in future we can add module auth and keep all of such functions. I made PR to delete it and this will solve last 2 errors with linting the code with ESLint

**Comment by kasp1** [comment]
Good idea.

**Comment by ilabacheuski** [comment]
#61 closed
