### ISSUE TITLE
Apiko server not listening 

### ISSUE THREAD

**Issue by prog-rajkamal** [apiko-rest-api/apiko#6]
Problem: apiko server is not running.

Steps to reproduce:
 1. install apiko-starter
 2. install apiko (with fix #5 )
 3. on apiko-starter, run `npm run dev`

More Info:
  When I run `npm run dev` on kasp1/apiko-starter, it shows me that 
  ![run_dev__server_not_listening](https://cloud.githubusercontent.com/assets/11518519/23585952/f34999b6-01b0-11e7-8fa8-ff7fac93d497.png)

Message of "server listening to port" is not shown, also apiko devui can not function due to this error.

System:
 OS:  Windows 8.1
 node: v5.7.0
 npm : v3.6.0
 console: git-bash

**Comment by prog-rajkamal** [comment]
Apiko does not support node v5.7.0 

Upgrade to v6 fixes this issue.

**Comment by prog-rajkamal** [comment]
@kasp1 is the dependency on node v6 is documented? node v4 LTS is supported till april 2018. so imo, node v6 requirement should be stated on https://apiko-rest-api.github.io/

**Comment by kasp1** [comment]
Did your fix also solve the problem with the server not starting up on node 5?

**Comment by prog-rajkamal** [comment]
no. this problem has been solved by upgrading node to v6.

**Comment by kasp1** [comment]
Hm I wonder what could be wrong there. :-/

**Comment by prog-rajkamal** [comment]
My best guess is some package requires updated node and is failing silently.
