### ISSUE TITLE
Problem using ProxyPass Apache

### ISSUE THREAD

**Issue by joelmandell** [apiko-rest-api/apiko#87]
Hello!
I have multiple webserver instances running on same ip, and using ProxyPass from apache to handle this.
For example I have domain bth.joelmandell.se that is a documentroot in apache and mwb-api.joelmandell.se that is the proxypass. I get an error when trying to reach the endpoint users in apiko: DNS lookup failure for: 192.168.0.108:5000users.
What can I do to fix this?

**Comment by kasp1** [comment]
No idea at this point @joelmandell . Feel free to privately message me on Gitter with exact URL so I can try things out.

Btw, it should be `192.168.0.108:5000/users`, but I doubt it's the problem.

**Comment by joelmandell** [comment]
![proxy apache](https://user-images.githubusercontent.com/109020/27508269-5162d544-58e1-11e7-808f-92e969015b7a.png)

**Comment by kasp1** [comment]
If you access Apiko without a proxy directly, does it work?

**Comment by joelmandell** [comment]
Yes without proxy it works

**Comment by kasp1** [comment]
Then it seems like there's rather a problem in the proxy setup. Personally, can't help with Apache much. :-(

**Comment by joelmandell** [comment]
Yep I messed up the config.
Before "ProxyPass / http://192.168.0.108:5000".
Change to "ProxyPass / http://192.168.0.108:5000/". And it is working :)
